# Configuração para deploy de um app Next.js no Netlify
# Modo: Server-Side Rendering com o plugin oficial do Next.js

[build]
  # Comando para instalar dependências e buildar o app Next.js
  command = "npm run build"
  # O plugin do Next.js sabe que deve publicar o diretório .next
  publish = ".next"

[build.environment]
  # Especifica a versão do Node.js para garantir compatibilidade
  NODE_VERSION = "18"

[[plugins]]
  # Essencial para deploy de apps Next.js no Netlify.
  # Lida com SSR, ISR, rotas de API, otimização de imagens, etc.
  package = "@netlify/plugin-nextjs"

# Headers de segurança para permitir que a calculadora seja embutida
# em um iframe na sua Landing Page do GoHighLevel.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://funil.solar.arkanlabs.com.br"
